import type { EntityKind } from './types'

export type FieldType =
  | 'text'
  | 'number'
  | 'day'
  | 'integer'
  | 'date'
  | 'bool'
  | 'enum'
  | 'category-ref'
  | 'instrument-ref'
  | 'member-ref'

export interface FieldSpec {
  key: string
  /** Canonical header text — what the template CSV and the download use. */
  column: string
  label: string
  description: string
  required: boolean
  /** Header spellings tried during auto-detect, `column` included. */
  aliases: string[]
  example: string
  /**
   * This field's value in the template's *second* example row. Defaults to
   * `required ? example : ''` — which is wrong for any field that's only
   * required under a condition (`required: false` here, but rejected by
   * validate.ts depending on another column), so those set it explicitly.
   * Getting this wrong ships a template whose own example row fails
   * validation; template.test.ts pins every row against buildPlan.
   */
  example2?: string
  type: FieldType
  enumValues?: readonly string[]
}

export const CATEGORY_FIELDS: FieldSpec[] = [
  {
    key: 'name',
    column: 'Name',
    label: 'Name',
    description: 'The category name.',
    required: true,
    aliases: ['name', 'category', 'category name'],
    example: 'Groceries',
    type: 'text',
  },
  {
    key: 'kind',
    column: 'Kind',
    label: 'Kind',
    description: 'Whether this category is for income or expense rows.',
    required: true,
    aliases: ['kind', 'type'],
    example: 'expense',
    type: 'enum',
    enumValues: ['income', 'expense'],
  },
  {
    key: 'parent',
    column: 'Parent',
    label: 'Parent category',
    description: 'The main category this is a sub-category of. Leave blank for a main category.',
    required: false,
    aliases: ['parent', 'parent category', 'main category'],
    example: '',
    type: 'text',
  },
  {
    key: 'icon',
    column: 'Icon',
    label: 'Icon',
    description: 'Optional icon key, matching the app’s icon set.',
    required: false,
    aliases: ['icon'],
    example: '',
    type: 'text',
  },
  {
    key: 'color',
    column: 'Color',
    label: 'Color',
    description: 'Optional hex color, e.g. #10b981.',
    required: false,
    aliases: ['color', 'colour'],
    example: '',
    type: 'text',
  },
]

export const ACCOUNT_FIELDS: FieldSpec[] = [
  {
    key: 'name',
    column: 'Name',
    label: 'Name',
    description: 'The account name.',
    required: true,
    aliases: ['name', 'account', 'account name'],
    example: 'Bank — Earth',
    type: 'text',
  },
  {
    key: 'type',
    column: 'Type',
    label: 'Type',
    description: 'What kind of account this is.',
    required: true,
    aliases: ['type', 'account type'],
    example: 'bank',
    type: 'enum',
    enumValues: ['bank', 'cash', 'ewallet'],
  },
  {
    key: 'owner',
    column: 'Owner',
    label: 'Owner',
    description: 'A household member’s name. Leave blank for a Common Pot (no single owner).',
    required: false,
    aliases: ['owner', 'person'],
    example: 'Earth',
    type: 'member-ref',
  },
  {
    key: 'openingBalance',
    column: 'Opening balance',
    label: 'Opening balance',
    description: 'The balance to start this account with. Requires Opening as of. Written as a Reconcile transaction, same as the app’s own Reconcile.',
    required: false,
    aliases: ['opening balance', 'balance', 'starting balance'],
    example: '15000',
    example2: '',
    type: 'number',
  },
  {
    key: 'openingAsOf',
    column: 'Opening as of',
    label: 'Opening as of',
    description: 'The date the opening balance was true. Requires Opening balance.',
    required: false,
    // Paired with Opening balance — set on row 1 because that row fills one
    // in, blank on row 2 because that row fills neither. Leaving this empty
    // while row 1 carried a balance made the "fully filled" example illegal.
    aliases: ['opening as of', 'as of', 'balance date'],
    example: '01/01/2026',
    example2: '',
    type: 'date',
  },
]

export const CARD_FIELDS: FieldSpec[] = [
  {
    key: 'name',
    column: 'Name',
    label: 'Name',
    description: 'The card name.',
    required: true,
    aliases: ['name', 'card', 'card name'],
    example: 'Card •• 1234',
    type: 'text',
  },
  {
    key: 'creditLimit',
    column: 'Credit limit',
    label: 'Credit limit',
    description: 'The card’s credit limit.',
    required: true,
    aliases: ['credit limit', 'limit'],
    example: '50000',
    type: 'number',
  },
  {
    key: 'statementDay',
    column: 'Statement day',
    label: 'Statement day',
    description: 'Day of the month the statement closes (1–31).',
    required: true,
    aliases: ['statement day', 'statement'],
    example: '20',
    type: 'day',
  },
  {
    key: 'dueDay',
    column: 'Due day',
    label: 'Due day',
    description: 'Day of the month payment is due (1–31).',
    required: true,
    aliases: ['due day', 'due'],
    example: '5',
    type: 'day',
  },
  {
    key: 'annualInterestRate',
    column: 'Annual interest rate',
    label: 'Annual interest rate',
    description: 'Percent per year. Leave blank for 0.',
    required: false,
    aliases: ['annual interest rate', 'interest rate', 'rate'],
    example: '',
    type: 'number',
  },
  {
    key: 'owner',
    column: 'Owner',
    label: 'Owner',
    description: 'A household member’s name. Leave blank for a Common Pot.',
    required: false,
    aliases: ['owner', 'person'],
    example: 'Earth',
    type: 'member-ref',
  },
]

export const INSTALLMENT_FIELDS: FieldSpec[] = [
  {
    key: 'name',
    column: 'Name',
    label: 'Name',
    description: 'The plan name.',
    required: true,
    aliases: ['name', 'item'],
    example: 'Laptop',
    type: 'text',
  },
  {
    key: 'startDate',
    column: 'Start date',
    label: 'Start date',
    description: 'The date of period 1.',
    required: true,
    aliases: ['start date'],
    example: '15/01/2026',
    type: 'date',
  },
  {
    key: 'totalPeriods',
    column: 'Total periods',
    label: 'Total periods',
    description: 'Number of installment periods.',
    required: true,
    aliases: ['total periods', 'periods'],
    example: '10',
    type: 'integer',
  },
  {
    key: 'monthlyAmount',
    column: 'Monthly amount',
    label: 'Monthly amount',
    description: 'Amount charged each period.',
    required: true,
    aliases: ['monthly amount', 'amount per period'],
    example: '1500',
    type: 'number',
  },
  {
    key: 'finalAmount',
    column: 'Final amount',
    label: 'Final amount',
    description: 'Amount of the last period, if it differs from the others. Leave blank if it doesn’t.',
    required: false,
    aliases: ['final amount'],
    example: '',
    type: 'number',
  },
  {
    key: 'category',
    column: 'Category',
    label: 'Category',
    description: 'An expense category name. Required — a plan with no category never posts any period.',
    required: true,
    aliases: ['category'],
    example: 'Electronics',
    type: 'category-ref',
  },
  {
    key: 'instrument',
    column: 'Account or card',
    label: 'Account or card',
    description: 'The account or card name this plan is billed to.',
    required: true,
    aliases: ['account or card', 'account', 'card', 'paying account'],
    example: 'Card •• 1234',
    type: 'instrument-ref',
  },
  {
    key: 'annualInterestRate',
    column: 'Annual interest rate',
    label: 'Annual interest rate',
    description: 'Percent per year. Leave blank for 0.',
    required: false,
    aliases: ['annual interest rate', 'interest rate', 'rate'],
    example: '',
    type: 'number',
  },
  {
    key: 'isCashAdvance',
    column: 'Cash advance',
    label: 'Cash advance',
    description: 'yes/no — whether this is a cash-advance plan.',
    required: false,
    aliases: ['cash advance', 'is cash advance'],
    example: '',
    type: 'bool',
  },
  {
    key: 'owner',
    column: 'Owner',
    label: 'Owner',
    description: 'A household member’s name.',
    required: false,
    aliases: ['owner', 'person'],
    example: '',
    type: 'member-ref',
  },
  {
    key: 'note',
    column: 'Note',
    label: 'Note',
    description: 'Optional note.',
    required: false,
    aliases: ['note'],
    example: '',
    type: 'text',
  },
  {
    key: 'status',
    column: 'Status',
    label: 'Status',
    description: 'Leave blank for active.',
    required: false,
    aliases: ['status'],
    example: '',
    type: 'enum',
    enumValues: ['active', 'done', 'cancelled'],
  },
  {
    key: 'periodsPaid',
    column: 'Periods paid',
    label: 'Periods paid',
    description: 'How many of the periods from the start are already settled. Backfills installment_payments for periods 1..N.',
    required: false,
    aliases: ['periods paid', 'paid'],
    example: '',
    type: 'integer',
  },
]

export const RECURRING_RULE_FIELDS: FieldSpec[] = [
  {
    key: 'name',
    column: 'Name',
    label: 'Name',
    description: 'The rule name.',
    required: true,
    aliases: ['name'],
    example: 'Netflix',
    type: 'text',
  },
  {
    key: 'kind',
    column: 'Kind',
    label: 'Kind',
    description: 'income, expense, or transfer.',
    required: true,
    aliases: ['kind', 'type'],
    example: 'expense',
    type: 'enum',
    enumValues: ['income', 'expense', 'transfer'],
  },
  {
    key: 'amount',
    column: 'Amount',
    label: 'Amount',
    description: 'The amount each occurrence.',
    required: true,
    aliases: ['amount'],
    example: '350',
    type: 'number',
  },
  {
    key: 'category',
    column: 'Category',
    label: 'Category',
    description: 'Required unless Kind is transfer.',
    required: false,
    aliases: ['category'],
    example: 'Subscriptions',
    example2: 'Subscriptions',
    type: 'category-ref',
  },
  {
    key: 'freq',
    column: 'Frequency',
    label: 'Frequency',
    description: 'weekly, monthly, or yearly.',
    required: true,
    aliases: ['frequency', 'freq'],
    example: 'monthly',
    type: 'enum',
    enumValues: ['weekly', 'monthly', 'yearly'],
  },
  {
    key: 'interval',
    column: 'Interval',
    label: 'Interval',
    description: 'Every N periods. Leave blank for 1.',
    required: false,
    aliases: ['interval'],
    example: '',
    type: 'integer',
  },
  {
    key: 'dayOfMonth',
    column: 'Day of month',
    label: 'Day of month',
    description: 'Required for monthly and yearly frequencies.',
    required: false,
    aliases: ['day of month'],
    example: '15',
    example2: '15',
    type: 'day',
  },
  {
    key: 'weekday',
    column: 'Weekday',
    label: 'Weekday',
    description: 'Required for weekly frequency. 0 = Sunday .. 6 = Saturday.',
    required: false,
    aliases: ['weekday'],
    example: '',
    type: 'integer',
  },
  {
    key: 'monthOfYear',
    column: 'Month of year',
    label: 'Month of year',
    description: 'Required for yearly frequency. 1 = January .. 12 = December.',
    required: false,
    aliases: ['month of year'],
    example: '',
    type: 'integer',
  },
  {
    key: 'monthEnd',
    column: 'Month-end rule',
    label: 'Month-end rule',
    description: 'clamp or skip, for a day-of-month that doesn’t exist in a short month. Leave blank for clamp.',
    required: false,
    aliases: ['month-end rule', 'month end'],
    example: '',
    type: 'enum',
    enumValues: ['clamp', 'skip'],
  },
  {
    key: 'startDate',
    column: 'Start date',
    label: 'Start date',
    description: 'The first date this rule applies from.',
    required: true,
    aliases: ['start date'],
    example: '15/01/2026',
    type: 'date',
  },
  {
    key: 'endDate',
    column: 'End date',
    label: 'End date',
    description: 'Optional — leave blank for open-ended.',
    required: false,
    aliases: ['end date'],
    example: '',
    type: 'date',
  },
  {
    key: 'instrument',
    column: 'Account or card',
    label: 'Account or card',
    description: 'The account or card this rule is charged from.',
    required: true,
    aliases: ['account or card', 'account', 'card'],
    example: 'Card •• 1234',
    type: 'instrument-ref',
  },
  {
    key: 'toInstrument',
    column: 'To account or card',
    label: 'To account or card',
    description: 'Required only when Kind is transfer.',
    required: false,
    aliases: ['to account or card', 'to account', 'to card'],
    example: '',
    type: 'instrument-ref',
  },
  {
    key: 'autoPost',
    column: 'Auto-post',
    label: 'Auto-post',
    description: 'yes/no — whether generated occurrences count immediately (yes) or wait for review (no, the default).',
    required: false,
    aliases: ['auto-post', 'auto post'],
    example: '',
    type: 'bool',
  },
  {
    key: 'variableAmount',
    column: 'Variable amount',
    label: 'Variable amount',
    description: 'yes/no — whether the amount changes between occurrences. Forces every occurrence into review.',
    required: false,
    aliases: ['variable amount'],
    example: '',
    type: 'bool',
  },
  {
    key: 'lastGeneratedDate',
    column: 'Last generated date',
    label: 'Last generated date',
    description: 'Leave blank to let the app backfill every occurrence from Start date to today on next open. Set to suppress backfilling before that date.',
    required: false,
    aliases: ['last generated date'],
    example: '',
    type: 'date',
  },
  {
    key: 'owner',
    column: 'Owner',
    label: 'Owner',
    description: 'A household member’s name.',
    required: false,
    aliases: ['owner', 'person'],
    example: '',
    type: 'member-ref',
  },
  {
    key: 'note',
    column: 'Note',
    label: 'Note',
    description: 'Optional note.',
    required: false,
    aliases: ['note'],
    example: '',
    type: 'text',
  },
  {
    key: 'active',
    column: 'Active',
    label: 'Active',
    description: 'yes/no. Leave blank for yes.',
    required: false,
    aliases: ['active'],
    example: '',
    type: 'bool',
  },
]

// The second example row is a **credit-card bill payment**: the one shape
// people reach for that isn't obvious from a column list, because it needs
// three columns to agree at once (Kind = transfer, Category blank, To
// account or card = the card). Paying a card bill is a transfer, never an
// expense — the spending was already recorded when the card was charged
// (D7), so filing the payment as an expense would double-count it and
// leave the card's outstanding untouched.
export const TRANSACTION_FIELDS: FieldSpec[] = [
  {
    key: 'date',
    column: 'Date',
    label: 'Date',
    description: 'The transaction date.',
    required: true,
    aliases: ['date', 'transaction date'],
    example: '03/01/2026',
    example2: '05/02/2026',
    type: 'date',
  },
  {
    key: 'kind',
    column: 'Kind',
    label: 'Kind',
    description: 'income, expense, or transfer.',
    required: true,
    aliases: ['kind', 'type'],
    example: 'expense',
    example2: 'transfer',
    type: 'enum',
    enumValues: ['income', 'expense', 'transfer'],
  },
  {
    key: 'amount',
    column: 'Amount',
    label: 'Amount',
    description: 'The transaction amount.',
    required: true,
    aliases: ['amount'],
    example: '250',
    example2: '3995',
    type: 'number',
  },
  {
    key: 'category',
    column: 'Category',
    label: 'Category',
    description: 'Required unless Kind is transfer.',
    required: false,
    aliases: ['category'],
    example: 'Groceries',
    example2: '',
    type: 'category-ref',
  },
  {
    key: 'instrument',
    column: 'Account or card',
    label: 'Account or card',
    description: 'Where the money came from.',
    required: true,
    aliases: ['account or card', 'account', 'card'],
    example: 'Bank — Earth',
    type: 'instrument-ref',
  },
  {
    key: 'toInstrument',
    column: 'To account or card',
    label: 'To account or card',
    description: 'Required only when Kind is transfer. For a card bill payment, this is the card being paid.',
    required: false,
    aliases: ['to account or card', 'to account', 'to card'],
    example: '',
    example2: 'Card •• 1234',
    type: 'instrument-ref',
  },
  {
    key: 'note',
    column: 'Note',
    label: 'Note',
    description: 'The ledger’s primary label — what shows as the row’s title.',
    required: false,
    aliases: ['note', 'description', 'label'],
    example: 'Coffee',
    example2: 'Card bill payment',
    type: 'text',
  },
  {
    key: 'description',
    column: 'Details',
    label: 'Details',
    description: 'Secondary detail, shown behind “+ Add details.”',
    required: false,
    aliases: ['details'],
    example: '',
    type: 'text',
  },
  {
    key: 'owner',
    column: 'Owner',
    label: 'Owner',
    description: 'A household member’s name. Leave blank to leave it unassigned.',
    required: false,
    aliases: ['owner', 'person'],
    example: '',
    type: 'member-ref',
  },
]

export const FIELD_SPECS: Record<EntityKind, FieldSpec[]> = {
  categories: CATEGORY_FIELDS,
  accounts: ACCOUNT_FIELDS,
  cards: CARD_FIELDS,
  installments: INSTALLMENT_FIELDS,
  recurringRules: RECURRING_RULE_FIELDS,
  transactions: TRANSACTION_FIELDS,
}

export const ENTITY_LABELS: Record<EntityKind, string> = {
  categories: 'Categories',
  accounts: 'Accounts',
  cards: 'Cards',
  installments: 'Installments',
  recurringRules: 'Recurring rules',
  transactions: 'Transactions',
}
